project_id = "aufmphldtjrcddyayqoy"

[functions.send-notification-email]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = true

[functions.extract-menu-from-image]
verify_jwt = true

[functions.maketou-webhook]
verify_jwt = false

[functions.create-maketou-checkout]
verify_jwt = true

[functions.generate-dish-image]
verify_jwt = true

[functions.team-member-auth]
verify_jwt = false

