import React, { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Building2, Copy, RefreshCw, Loader2 } from 'lucide-react';
import { toast } from 'sonner';

/**
 * Displays the unique restaurant code used by team members to log in via PIN.
 * Read from `profiles.restaurant_code`. Auto-generated by trigger if missing.
 */
export const RestaurantCodeCard: React.FC = () => {
  const { user, isTeamMember, teamMemberSession } = useAuth();
  const ownerId = isTeamMember ? teamMemberSession?.ownerId : user?.id;
  const [code, setCode] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  const load = async () => {
    if (!ownerId) return;
    setLoading(true);
    let { data } = await supabase
      .from('profiles')
      .select('restaurant_code')
      .eq('id', ownerId)
      .maybeSingle();

    // Fallback: générer si manquant (uniquement pour le propriétaire connecté)
    if (!data?.restaurant_code && !isTeamMember && user?.id === ownerId) {
      const newCode = 'QX-' + Math.random().toString(36).slice(2, 7).toUpperCase();
      await supabase.from('profiles').update({ restaurant_code: newCode }).eq('id', ownerId);
      const refetch = await supabase
        .from('profiles').select('restaurant_code').eq('id', ownerId).maybeSingle();
      data = refetch.data;
    }
    setCode(data?.restaurant_code || null);
    setLoading(false);
  };

  useEffect(() => { load(); }, [ownerId]);

  const copy = () => {
    if (!code) return;
    navigator.clipboard.writeText(code);
    toast.success('Code copié', { description: code });
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Building2 className="w-5 h-5" /> Code restaurant
        </CardTitle>
        <CardDescription>
          Partagez-le avec votre équipe. Ils se connectent avec : ce code + leur pseudo + leur PIN.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {loading ? (
          <div className="flex items-center gap-2 text-muted-foreground">
            <Loader2 className="w-4 h-4 animate-spin" /> Chargement…
          </div>
        ) : (
          <div className="flex items-center gap-3">
            <div className="font-mono text-2xl tracking-widest bg-muted px-4 py-2 rounded-md select-all">
              {code || '—'}
            </div>
            <Button variant="outline" size="sm" onClick={copy} disabled={!code}>
              <Copy className="w-4 h-4 mr-1" /> Copier
            </Button>
            <Button variant="ghost" size="sm" onClick={load} title="Recharger">
              <RefreshCw className="w-4 h-4" />
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
};
